---
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    cache = FALSE,
    warning = FALSE,
    message = FALSE,
    fig.align = "center"
)

library(tidyverse)
library(here)
library(glue)
library(mildsvm)
library(patchwork)
library(knitr)
library(kableExtra)
source(here("analysis/utils.R"))

res_dir <- "output"
fig_dir <- "fig"

theme_set(theme_minimal())

# Tables
kable_standard <- function(...) {
    kable(booktabs = TRUE, linesep = "", ...) %>% 
        kable_styling(full_width = FALSE)
}
```


```{r}
methods_to_show <- tribble(
  ~method, ~short_name, ~color, 
  "MISVM (qp-heuristic radial univariate cor)", "MI-SVM (UNIV1, UNIV2, COR)", "#13317DFF",
  "MISVM (qp-heuristic radial baseline cor)", "MI-SVM (UNIV1, COR)", "#434C99FF",
  "MISVM (qp-heuristic radial univariate)", "MI-SVM (UNIV1, UNIV2)", "#5F66AFFF",
  "MISVM (qp-heuristic radial baseline)", "MI-SVM (UNIV1)", "#7180C1FF",
  "SMM ()", "SI-SMM", "#79D1D1FF",
  "MILDSVM (qp-heuristic)", "MI-SMM (HEURISTIC)", "#EB7157FF",
  "MILDSVM (mip)", "MI-SMM (MIQP)", "#F5542CFF",
)

```


```{r}
create_results_plot2 <- function(data, x, methods, facets = ninst + nsample ~ nbag,
                                 alpha = 0.5) {
  data %>% 
    ggplot(aes(x = {{ x }} , y = method_name, color = method_name)) +
    ggbeeswarm::geom_quasirandom(
      aes(color = method_name, group = method_name),
      groupOnX = FALSE, 
      alpha = alpha
    ) +
    # geom_vline(xintercept = 0.5, color = "grey40") +
    geom_errorbarh(stat = "summary",
                   fun.min = mean, fun.max = mean, 
                   color = "grey10") + 
    facet_grid(facets, 
               labeller = label_both) + 
    scale_y_discrete(limits = methods$method,
                     labels = methods$short_name) +
    scale_color_manual(limits = methods$method,
                       labels = methods$short_name,
                       values = methods$color) +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(title = "Comparing replications of CV procedure across methods", 
         y = NULL)
}

```

## Simulation experiment 

```{r}


sims <- c("1.0.0", "2.0.0", "3.0.0", "4.0.0",
          "1.0.1", "2.0.1", "3.0.1", "4.0.1")

results <- 
  map(sims, ~read_results(.x, res_dir)) %>% 
  bind_rows()

data_param <- 
  map(sims, ~read_data_param(.x, res_dir)) %>% 
  bind_rows()

results_mod <- results %>% 
  left_join(data_param, by = c("train_name", "sim")) %>% 
  hoist(control, "kernel") %>% 
  mutate(method_name = glue("{str_to_upper(fun)} (",
                            "{ifelse(is.na(method), '', glue('{method}'))}",
                            "{ifelse(fun == 'misvm', glue(' {kernel} '), '')}", 
                            "{ifelse(fun == 'misvm', names(.fns), '')}",
                            "{ifelse(fun == 'misvm', ifelse(cor, ' cor', ''), '')})"),
         sim = str_sub(sim, 1, 3)) %>% 
  select(method_name, everything())

sim_labels <- c(
  "1.0" = "1. Multivariate t vs multivariate normal",
  "2.0" = "2. Covariance differences",
  "3.0" = "3. Mean differences",
  "4.0" = "4. Large covariance differences"
)

```


```{r, eval=FALSE}
# How long did simulations take?
# results_mod %>% 
#   filter(nbag == 100, ninst == 3, nsample == 50) %>% 
#   create_results_plot2(x = time, methods_to_show) + 
#   facet_wrap(~sim, labeller = labeller(sim = sim_labels), ncol = 2) +
#   labs(title = NULL)

```


```{r}
for (s in unique(str_sub(sims, 1, 3))) {
  
  p <- 
    results_mod %>% 
    filter(str_sub(sim, 1, 3) == s) %>% 
    mutate(time_hr = time / 60 / 60) %>% 
    rename(`N group` = nbag,
           `N instance` = ninst,
           `N sample` = nsample) %>% 
    create_results_plot2(
      x = time_hr, 
      methods = methods_to_show,
      facets = `N group` ~ `N instance` + `N sample`
    ) + 
    labs(title = NULL, x = "Time (hr)")
  
  print(p)
  fname <- glue("mildsvm-sims-appendix_time-plot_revision_{s}.pdf")
  ggsave(here(fig_dir, fname), p, width = 8, height = 4)
}
```



## DCIS data 

```{r}

sims <- c("5.0.0")
steps <- c(2)
res_dir <- "output"

results <- 
  map2(sims, steps, ~read_results(.x, res_dir, step = .y)) %>% 
  bind_rows()

results_mod <- results %>% 
  hoist(control, "kernel") %>% 
  mutate(method_name = glue("{str_to_upper(fun)} (",
                            "{ifelse(is.na(method), '', glue('{method}'))}",
                            "{ifelse(fun == 'misvm', glue(' {kernel} '), '')}", 
                            "{ifelse(fun == 'misvm', names(.fns), '')}",
                            "{ifelse(fun == 'misvm', ifelse(cor, ' cor', ''), '')})"),
         sim = str_sub(sim, 1, 3)) %>% 
  select(method_name, sim, everything())

results_mod <-
  results_mod %>% 
  group_by(method_name, fun, method, kernel, .fns, cor, rep) %>% 
  summarize(auc = mean(auc), 
            time = sum(time) + sum(sum_time),
            .groups = "drop_last")

```

```{r}
p <- results_mod %>% 
  mutate(time_hr = time / 60 / 60) %>% 
  create_results_plot2(
    x = time_hr, 
    methods = methods_to_show,
    facets = NULL
  ) + 
  scale_x_continuous(labels = scales::number_format(big.mark = ",")) + 
  labs(title = NULL, x = "Time (hr)")

p
```

```{r}
table_type <- "html" # "latex"

metrics <-
  results_mod %>% 
  filter(method_name %in% methods_to_show$method) %>%
  mutate(time_hr = time / 60 / 60) %>% 
  summarize(
    time_mean = mean(time_hr),
    time_sd = sd(time_hr),
    .groups = "drop"
  ) %>% 
  arrange(factor(method_name, levels = rev(methods_to_show$method)))

tbl <- metrics %>% 
  left_join(methods_to_show, by = c("method_name" = "method")) %>% 
  select(short_name, time_mean, time_sd)
```


```{r fiber-results}
tbl %>% 
  kable_standard(caption = "Summary of Total Time",
                 col.names = c("Method", "Mean", "SD"),
                 align = "lrr",
                 escape = FALSE,
                 digits = 1) %>% 
  add_header_above(c(" " = 1, "Time (hr)" = 2))

```

Note that for the fiber features data, the following methods use the pre-computed kernel matrix: SI-SMM, MI-SMM (MIQP), MI-SMM (Heuristic). It was not recorded how long the computation of the kernel matrix took, but it was between 1 hour and 1 day from memory.
